// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvmmbhzzkdusswvlkgkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bW1iaHp6a2R1c3N3dmxrZ2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjYxODIsImV4cCI6MjA3MzQwMjE4Mn0.GHb98JmfP1GWqNckdgmozKeLB2EDrxxRc5p0ho7uyHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});